### ISSUE TITLE
find-free-port returning the same already used port

### ISSUE THREAD

**Issue by c0debreaker** [mhzed/find-free-port#5]
This is my code which launches netcat as a tcp listener. It picks 3001 on my first call. When I make another api POST call while the other earlier call is still active, it picks 3001 again and not 3002.

```
app.post('/w/upload', multer({ storage: storage }).single('upl'), (req, res) => {
  fp(3000, 3100, (err, freePort) => {
    console.log('free port is', freePort);
    child = exec(`nc -l ${freePort}`, (error, stdout, stderr) => {
      console.log(req.file);
      console.log('stdout: ' + stdout);
      console.log('stderr: ' + stderr);
      if (error !== null) {
        console.log('exec error: ' + error);
      }
      res.status(200).json({status: req.file});
    });
  });
})
```

Here is the screenshot on my console - https://i.imgur.com/VBiiJKr.png

**Comment by mhzed** [comment]
It's a known issue:  'listen' seems to always succeed even if other processes are already listening.
I've uploaded a new version that uses 'connect' to determine 'freeness' of the port, it should fix this issue.

**Comment by leonaves** [comment]
This isn't fixed. If I run:

```
php -S localhost:8080
```

And then this, it does not detect that PHP is listening on port 8080, and assigns it anyway.

**Comment by leonaves** [comment]
It seems that the PHP webserver will listen on `::1` (IPv6) rather than `127.0.0.1` and most browsers will resolve to `::1` if available, and fallback to `127.0.0.1`. This is actually quite funny. Because of the round-robin resolution strategy of localhost here, you can never actually rely on a particular port to not be assigned on it. Even if you successfully get node to listen on port `127.0.0.1:8080`, another process could just come along, start listening on `::1:8080` and suck all its traffic away when you visit `localhost` 😂 

Don't know what the correct behaviour is here to be honest...

**Comment by Heath123** [comment]
> 
> 
> It's a known issue: 'listen' seems to always succeed even if other processes are already listening.
> I've uploaded a new version that uses 'connect' to determine 'freeness' of the port, it should fix this issue.
@mhzed What about doing both? This says that ports are free when the program doesn't have permission to access them
